model_params:
  gamma: 0.9
  layer_norm: True
  actor_hid_sizes: [64, 64, 32]
  critic_hid_sizes: [64, 32]
  actor_nonlinearity: 'elu'
  critic_nonlinearity: 'elu'
  critic_lr: 0.0002
  actor_lr: 0.0001
  num_act: 18

train_params:
  num_episodes: 100000000
  episode_runs: 10
  best_ratio: 0.1
  n_runs: 1
  init_sigma: 0.02
  sigma_constr_start: 0.0
  sigma_constr_end: 0.0
  sigma_constr_steps: 1000

env_params:
  env:
    max_obstacles: 10
    skip_frame: 1
    reward_mult: 10
    fall_penalty: -0.0
  state_transform:
    centr_state: 'pelvis_x'
    vel_states: []
    obstacles_mode: 'standard'
    exclude_centr: True
    predict_bodies: False
    add_step: False